//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseYchPractic.DbEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int ID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Structure { get; set; }
        public int Id_PointOfIssue { get; set; }
        public Nullable<int> Id_Fio { get; set; }
        public int Id_Status { get; set; }
        public int Id_InformationEndOrder { get; set; }
    
        public virtual InformationEndOrder InformationEndOrder { get; set; }
        public virtual UserData UserData { get; set; }
        public virtual PointOfIssue PointOfIssue { get; set; }
        public virtual StatysProduct StatysProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
